stages:         
  - build

build-job:      
  stage: build
  image: maven:3-jdk-11
  script:
    - cd datawiz-api
    - mvn clean
  rules:
    - changes:
        paths:
          - datawiz-api/*
  tags:
      - ugrad
    
front-job:
  stage: build
  image: node:18.13.0
  script:
    - cd Front-End
    - npx yarn
    - npx yarn build
  rules:
    - changes:
        paths:
          - Front-End/*
  tags:
      - ugrad

