default:
    image: maven:latest

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd datawiz-api
    - mvn compile
  rules:
    - changes:
        - datawiz-api/*
  tags:
      - ugrad
    
front-job:
  stage: build
  image: node:18.13.0
  script:
    - cd Front-End
    - npx yarn
    - npx yarn build
  rules:
    - changes:
        - Front-End/*
  tags:
      - ugrad

