stages:         
  - build
  - smells

build-job:      
  stage: build
  image: maven:3-jdk-17
  script:
    - cd datawiz-api
    - mvn clean
  rules:
    - changes:
        paths:
          - datawiz-api/*
  tags:
      - ugrad
    
front-job:
  stage: build
  image: node:18.13.0
  script:
    - cd Front-End
    - npx yarn
    - npx yarn build
  rules:
    - changes:
        paths:
          - Front-End/*
  tags:
      - ugrad

smell-backend-job:
    stage: smells
    image: openjdk:11
    script:
      - java -jar $CI_PROJECT_DIR/DesignateJava/DesigniteJava.jar -i $CI_PROJECT_DIR/datawiz-api -o $CI_PROJECT_DIR/DesignateJava/DesignateOutput/
    tags:
      - ugrad