include:
  remote: 'https://gitlab.openxcell.dev/public-resources/gitlab-ci/-/raw/master/templates/build.yaml'
stages:
  - build
  - deploy
variables:
  NGINX_PATH: "/home/ubuntu/docker-stack/nginx_conf/react"
  PROJECT: "jail-commissary"
build: 
  stage: build
  extends: .build_static

deploy_dev:
  stage: deploy
  extends: .deploy_static
  only:
    - development    
